import { Plugins } from './Plugins';
import { Maintenance, Presets } from './Maintenance';
import { Resources } from './Resources';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { components } from '../api/schema';
import { changeAccount } from '../accounts/session';
import { PageShell, Pager, Problem } from '../public/Public';

type AdminAction = components['schemas']['AdminAction']['action'];
export function Setup() {
  const cache = useQueryClient();
  const status = useQuery({ queryKey: ['setup'], queryFn: ({ signal }) => result(client.GET('/api/v1/setup', { signal })) });
  const create = useMutation({ mutationFn: (f: FormData) => result(client.POST('/api/v1/setup', { body: { token: String(f.get('token')), email: String(f.get('email')), display_name: String(f.get('display_name')), password: String(f.get('password')) } })), onSuccess: async u => { await changeAccount(cache, u); window.location.assign('/admin'); } });
  return <PageShell title="初始化你的 AniMemo">{status.isPending ? <p>正在检查实例…</p> : status.error ? <Problem error={status.error} /> : !status.data.available ? <p>初始化入口已关闭。已初始化的实例请登录管理员账号；新实例请由部署者配置初始化口令后再打开此页。</p> : <form className="editor-form setup-form" onSubmit={e => { e.preventDefault(); create.mutate(new FormData(e.currentTarget)); }}><p>使用部署时生成的初始化口令创建第一位管理员。此入口只能完成一次。</p><fieldset disabled={create.isPending}><label>初始化口令<input name="token" type="password" autoComplete="off" minLength={32} required /></label><label>管理员昵称<input name="display_name" maxLength={32} required /></label><label>管理员邮箱<input name="email" type="email" required /></label><label>管理员密码<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={72} required /></label><button className="button primary">创建管理员</button></fieldset>{create.error && <Problem error={create.error} />}</form>}</PageShell>;
}
const actionLabels: Record<AdminAction, string> = { 'grant-admin': '授予管理员', 'remove-admin': '移除管理员', disable: '停用账号', enable: '恢复账号', 'revoke-sessions': '撤销登录', 'approve-public': '通过公开申请', 'reject-public': '拒绝公开申请', 'hide-public': '下架公开手账' };
export function Admin() {
  const [tab, setTab] = useState<'users' | 'resources' | 'site' | 'audit' | 'health' | 'presets' | 'plugins'>('users');
  return <PageShell title="实例管理"><nav className="filter-tabs" aria-label="管理导航">{(['users','resources','presets','plugins','site','health','audit'] as const).map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{{ plugins: '插件', health: '健康与维护', presets: '标签预设', resources: '资源与专栏审核', users: '用户与公开审核', site: '站点设置', audit: '操作审计' }[t]}</button>)}</nav>{tab === 'plugins' ? <Plugins /> : tab === 'users' ? <Users /> : tab === 'health' ? <Maintenance /> : tab === 'presets' ? <Presets /> : tab === 'resources' ? <Resources /> : tab === 'site' ? <SiteSettings /> : <Audit />}</PageShell>;
}
function Users() {
  const cache = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [state, setState] = useState<'' | 'pending' | 'published' | 'disabled'>('');
  const [selected, setSelected] = useState<{ user: components['schemas']['AdminUser']; action: AdminAction } | null>(null);
  const q = useQuery({ queryKey: ['admin', 'users', search, state, page], queryFn: ({ signal }) => result(client.GET('/api/v1/admin/users', { signal, params: { query: { search, state, page } } })) });
  const apply = useMutation({ mutationFn: (f: FormData) => { if (!selected) throw new Error('请选择账号'); return result(client.POST('/api/v1/admin/users/{id}', { params: { path: { id: selected.user.id } }, body: { action: selected.action, version: selected.user.version, reason: String(f.get('reason')) } })); }, onSuccess: async () => { setSelected(null); await cache.invalidateQueries({ queryKey: ['admin'] }); await cache.invalidateQueries({ queryKey: ['session'] }); } });
  return <><div className="search-toolbar"><label className="search-field">搜索用户<input value={search} maxLength={160} onChange={e => { setSearch(e.target.value); setPage(1); }} /></label><label>筛选<select value={state} onChange={e => { setState(e.target.value as typeof state); setPage(1); }}><option value="">全部</option><option value="pending">待审核公开申请</option><option value="published">已公开</option><option value="disabled">已停用</option></select></label></div>{q.isPending ? <p>正在读取用户…</p> : q.error ? <Problem error={q.error} /> : <><div className="admin-list">{q.data.items.map(u => <article key={u.id} className="admin-row"><div><h2>{u.display_name} {u.is_admin && <small>管理员</small>}</h2><p>{u.email} · {u.disabled ? '已停用' : '正常'} · {{ private: '未公开', pending: '公开待审', published: '已公开', rejected: '已拒绝 / 下架' }[u.public_state]}</p>{u.bio && <p>{u.bio}</p>}{u.public_reason && <p>审核说明：{u.public_reason}</p>}</div><div className="management-actions">{([u.is_admin ? 'remove-admin' : 'grant-admin', u.disabled ? 'enable' : 'disable', 'revoke-sessions', ...(u.public_state === 'pending' ? ['approve-public', 'reject-public'] : []), ...(u.public_state === 'published' ? ['hide-public'] : [])] as AdminAction[]).map(action => <button className="button secondary" key={action} onClick={() => { apply.reset(); setSelected({ user: u, action }); }}>{actionLabels[action]}</button>)}</div></article>)}</div><Pager page={page} total={q.data.total} size={20} onChange={setPage} /></>}{selected && <section className="admin-confirm" aria-label="确认管理操作"><h2>{actionLabels[selected.action]}：{selected.user.display_name}</h2><p>权限变更、停用和撤销登录会让该账号退出所有设备。操作会写入审计记录。</p><form className="editor-form" onSubmit={e => { e.preventDefault(); apply.mutate(new FormData(e.currentTarget)); }}><label>操作原因<textarea name="reason" maxLength={400} required={['reject-public','hide-public'].includes(selected.action)} /></label><div className="management-actions"><button className="button primary" disabled={apply.isPending}>确认执行</button><button type="button" className="button quiet" disabled={apply.isPending} onClick={() => setSelected(null)}>取消</button></div>{apply.error && <Problem error={apply.error} />}</form></section>}</>;
}
function SiteSettings() {
  const cache = useQueryClient(); const q = useQuery({ queryKey: ['site'], queryFn: ({ signal }) => result(client.GET('/api/v1/site', { signal })) }); const [saved, setSaved] = useState(false);
  const save = useMutation({ mutationFn: (f: FormData) => result(client.PUT('/api/v1/admin/site', { body: { name: String(f.get('name')), description: String(f.get('description')), registration_open: f.has('registration_open'), version: Number(f.get('version')) } })), onSuccess: data => { cache.setQueryData(['site'], data); setSaved(true); } });
  if (q.isPending) return <p>正在读取设置…</p>; if (q.error) return <Problem error={q.error} />;
  return <form key={q.data.version} className="editor-form setup-form" onSubmit={e => { e.preventDefault(); save.mutate(new FormData(e.currentTarget)); }}><input type="hidden" name="version" value={q.data.version} /><label>站点名称<input name="name" defaultValue={q.data.name} maxLength={60} required /></label><label>站点简介<textarea name="description" defaultValue={q.data.description} maxLength={400} /></label><label className="check-label"><input type="checkbox" name="registration_open" defaultChecked={q.data.registration_open} />开放注册</label><button className="button primary" disabled={save.isPending}>保存站点设置</button>{saved && <p role="status">站点设置已保存</p>}{save.error && <Problem error={save.error} />}</form>;
}
function Audit() {
  const [page, setPage] = useState(1); const q = useQuery({ queryKey: ['admin','audit',page], queryFn: ({ signal }) => result(client.GET('/api/v1/admin/audit', { signal, params: { query: { page } } })) });
  return q.isPending ? <p>正在读取审计…</p> : q.error ? <Problem error={q.error} /> : <><div className="admin-list">{q.data.items.map(e => <article className="admin-row" key={e.id}><strong>{e.actor || '已注销账号'} · {actionLabels[e.action as AdminAction] || e.action}</strong><time>{new Date(e.created_at).toLocaleString()}</time><p>{e.kind} / {e.target}</p><pre>{JSON.stringify(e.detail, null, 2)}</pre></article>)}</div><Pager page={page} total={q.data.total} size={30} onChange={setPage} /></>;
}
