import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { components } from '../api/schema';
import { Problem } from '../public/Public';
import { Storage } from './Storage';
const size = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MiB`;
export function Maintenance() {
  const cache = useQueryClient(); const [confirm,setConfirm] = useState(false);
  const q = useQuery({ queryKey:['admin','status'],queryFn:({signal})=>result(client.GET('/api/v1/admin/status',{signal})),refetchInterval:30000 });
  const clean = useMutation({ mutationFn:()=>result(client.POST('/api/v1/admin/maintenance',{body:{action:'clear-expired'}})),onSuccess:async()=>{setConfirm(false);await cache.invalidateQueries({queryKey:['admin']});} });
  return <section className="settings-section">{q.isPending?<p>正在检查实例…</p>:q.error?<Problem error={q.error}/>:<><h2>实例健康与存储</h2><p>数据库：{q.data.database==='ready'?'连接正常':q.data.database} · 检查时间 {new Date(q.data.server_time).toLocaleString()}</p><div className="stats-grid">{[['账号',q.data.users],['番剧（含回收站）',q.data.entries],['专栏（含回收站）',q.data.columns],['活动导入任务',q.data.imports_active]].map(([name,value])=><div className="stat-card" key={name}><p>{name}</p><strong className="stat-value">{value}</strong></div>)}</div><p>整个数据库占用 {size(q.data.database_bytes)}；图片总用量 {size(q.data.media_bytes)}。</p><h3>图片使用量最高的账号</h3><div className="admin-list">{q.data.owners.map(o=><div className="admin-row" key={o.id}>{o.name}<span> · {size(o.bytes)}</span></div>)}</div><h3>清理过期数据</h3><p>{q.data.expired_sessions} 个过期登录。仅清理已过期的登录、已结束且过期的导入任务、未完成的过期验证器设置。</p><button className="button secondary" onClick={()=>setConfirm(true)}>清理过期数据</button>{confirm&&<div className="delete-confirm"><p>确认清理以上过期数据？有效登录、番剧和观看记录会保留。</p><button className="button primary" disabled={clean.isPending} onClick={()=>clean.mutate()}>确认清理</button><button className="button quiet" onClick={()=>setConfirm(false)}>取消</button></div>}{clean.data&&<p role="status">清理完成：{clean.data.sessions} 个登录、{clean.data.imports} 个导入任务、{clean.data.enrollments} 个验证器设置。</p>}{clean.error&&<Problem error={clean.error}/>}</>}<Storage/></section>;
}
export function Presets() {
 const cache=useQueryClient();const [editing,setEditing]=useState<components['schemas']['Preset']|null>(null);
 const q=useQuery({queryKey:['presets'],queryFn:({signal})=>result(client.GET('/api/v1/presets',{signal}))});
 const save=useMutation({mutationFn:(f:FormData)=>result(client.PUT('/api/v1/admin/presets',{body:{name:String(f.get('name')),color:String(f.get('color')),version:editing?.version||0}})),onSuccess:async()=>{setEditing(null);await cache.invalidateQueries({queryKey:['presets']});}});
 const remove=useMutation({mutationFn:(p:components['schemas']['Preset'])=>result(client.DELETE('/api/v1/admin/presets',{body:p})),onSuccess:()=>cache.invalidateQueries({queryKey:['presets']})});
 return <section className="settings-section"><h2>全站标签预设</h2><p>用户可以将预设保存为自己的标签颜色。更新或删除预设不会覆盖用户已保存的设置。</p><form key={editing?.name||'new'} className="editor-form setup-form" onSubmit={e=>{e.preventDefault();save.mutate(new FormData(e.currentTarget));}}><label>预设名称<input name="name" defaultValue={editing?.name} readOnly={!!editing} maxLength={24} required/></label><label>预设颜色<input name="color" type="color" defaultValue={editing?.color||'#8974cc'}/></label><div className="management-actions"><button className="button primary" disabled={save.isPending}>保存标签预设</button>{editing&&<button type="button" className="button quiet" onClick={()=>setEditing(null)}>取消编辑</button>}</div></form>{q.isPending?<p>正在读取预设…</p>:q.error?<Problem error={q.error}/>:<div className="admin-list">{q.data.items.map(p=><article className="admin-row" key={p.name}><strong>{p.name}</strong><span> · {p.color}</span><div className="management-actions"><button className="button secondary" onClick={()=>setEditing(p)}>修改 {p.name}</button><button className="button quiet" disabled={remove.isPending} onClick={()=>remove.mutate(p)}>删除 {p.name}</button></div></article>)}</div>}{(save.error||remove.error)&&<Problem error={save.error||remove.error}/>}</section>;
}
