import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Icon } from '../components/ui/Icon';
import { Dialog } from '../components/ui/Dialog';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { components } from '../api/schema';
import { Problem } from '../public/Public';
import { Storage } from './Storage';
import { useAdminStatus, useRuntime, formatSize, formatTime } from './data';

export function Maintenance() {
  const cache = useQueryClient();
  const [confirm, setConfirm] = useState(false);
  const q = useAdminStatus();
  const runtime = useRuntime();
  const clean = useMutation({ mutationFn: () => result(client.POST('/api/v1/admin/maintenance', { body: { action: 'clear-expired' } })), onSuccess: async () => { setConfirm(false); await cache.invalidateQueries({ queryKey: ['admin'] }); } });
  return <div className="admin-stack">
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>实例运行状态</h2><p>{q.data ? `最近检查 ${formatTime(q.data.server_time)}` : '自动检查数据库连接'}</p></div><span className="admin-tile-icon green"><Icon name="server" /></span></div>{q.isPending ? <div className="admin-empty" role="status">正在检查实例…</div> : q.error ? <Problem error={q.error} /> : <><div className="admin-service-list"><div><span>PostgreSQL 数据库</span><span className={`admin-badge ${q.data.database === 'ready' ? 'green' : 'amber'}`}>{q.data.database === 'ready' ? '连接正常' : q.data.database}</span></div></div><div className="admin-storage-numbers"><div><span>数据库占用</span><strong>{formatSize(q.data.database_bytes)}</strong></div><div><span>图片用量</span><strong>{formatSize(q.data.media_bytes)}</strong></div></div></>}</section>
      <section className="admin-panel"><div className="admin-panel-heading"><div><h2>后台任务</h2><p>独立任务进程 · 每 10 秒刷新</p></div><span className={`admin-badge ${runtime.data?.worker_ready ? 'green' : 'amber'}`}>{runtime.data ? runtime.data.worker_ready ? '运行中' : '暂时离线' : runtime.error ? '读取失败' : '检查中'}</span></div>{runtime.isPending ? <div className="admin-empty" role="status">正在读取任务状态…</div> : runtime.error ? <Problem error={runtime.error} /> : <><div className="admin-job-counts"><div><strong>{runtime.data.pending}</strong><span>待处理</span></div><div><strong>{runtime.data.running}</strong><span>执行中</span></div><div><strong>{runtime.data.done}</strong><span>已完成</span></div><div><strong>{runtime.data.failed}</strong><span>失败</span></div></div><p className="admin-panel-note">{runtime.data.worker_ready ? '提交后的任务由独立进程持续处理。' : '任务已持久保存，进程恢复后会继续处理。'}</p></>}</section></div>
    <Storage />
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>图片用量排行</h2><p>图片使用量最高的账号</p></div><Icon name="users" /></div>{q.data ? q.data.owners.length ? <div className="admin-owner-list">{q.data.owners.map((owner, i) => <div key={owner.id}><span className="admin-rank">{String(i + 1).padStart(2, '0')}</span><span>{owner.name}</span><strong>{formatSize(owner.bytes)}</strong></div>)}</div> : <div className="admin-empty">还没有图片用量记录。</div> : <div className="admin-empty">{q.error ? '用量读取失败' : '正在读取用量…'}</div>}</section>
      <section className="admin-panel"><div className="admin-panel-heading"><div><h2>日常清理</h2><p>移除已经过期的临时数据</p></div><Icon name="trash" /></div><div className="admin-panel-body"><p>过期登录 <strong>{q.data?.expired_sessions ?? '—'}</strong> 个</p><p className="admin-muted">同时清理已过期的已结束导入任务、未完成的验证器设置。有效登录与手账内容会保留。</p><Button className="button secondary" disabled={!q.data || clean.isPending} onClick={() => { clean.reset(); setConfirm(true); }}>清理过期数据</Button>{clean.data && <p role="status">清理完成：{clean.data.sessions} 个登录、{clean.data.imports} 个导入任务、{clean.data.enrollments} 个验证器设置。</p>}{!confirm && clean.error && <Problem error={clean.error} />}</div></section></div>
    {confirm && <Dialog title="清理过期数据" onClose={() => { if (!clean.isPending) setConfirm(false); }}><div className="admin-dialog-form"><p>确认清理已过期的登录、导入任务和验证器设置？有效登录、番剧和观看记录会保留。</p><div className="admin-form-actions"><Button className="button secondary" disabled={clean.isPending} onClick={() => setConfirm(false)}>取消</Button><Button className="button primary" disabled={clean.isPending} onClick={() => clean.mutate()}>确认清理</Button></div>{clean.error && <Problem error={clean.error} />}</div></Dialog>}
  </div>;
}
export function Presets() {
  const cache = useQueryClient();
  const [editing, setEditing] = useState<components['schemas']['Preset'] | null>(null);
  const [generation, setGeneration] = useState(0);
  const q = useQuery({ queryKey: ['presets'], queryFn: ({ signal }) => result(client.GET('/api/v1/presets', { signal })) });
  const save = useMutation({ mutationFn: (form: FormData) => result(client.PUT('/api/v1/admin/presets', { body: { name: String(form.get('name')), color: String(form.get('color')), version: editing?.version || 0 } })), onSuccess: async () => { setEditing(null); setGeneration(n => n + 1); await cache.invalidateQueries({ queryKey: ['presets'] }); } });
  const remove = useMutation({ mutationFn: (preset: components['schemas']['Preset']) => result(client.DELETE('/api/v1/admin/presets', { body: preset })), onSuccess: async (_, preset) => { if (editing?.name === preset.name) setEditing(null); await cache.invalidateQueries({ queryKey: ['presets'] }); } });
  return <div className="admin-columns admin-presets-layout"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>全站标签{q.data && <span className="admin-count">{q.data.items.length}</span>}</h2><p>显示在番剧和札记的标签选择中</p></div><Icon name="tag" /></div>{q.isPending ? <div className="admin-empty" role="status">正在读取预设…</div> : q.error ? <Problem error={q.error} /> : !q.data.items.length ? <div className="admin-empty"><Icon name="tag" /><h3>给记忆添一点颜色</h3><p>创建第一个预设，例如「日常」或「冒险」。</p></div> : <div className="admin-preset-list">{q.data.items.map(preset => <div key={preset.name}><span className="admin-color-dot" style={{ background: preset.color }} /><div><strong>{preset.name}</strong><small>{preset.color}</small></div><div className="management-actions"><Button className="icon-button" aria-label={`修改 ${preset.name}`} disabled={save.isPending || remove.isPending} onClick={() => { save.reset(); setEditing(preset); }}><Icon name="edit" /></Button><Button className="icon-button" aria-label={`删除 ${preset.name}`} disabled={remove.isPending || save.isPending} onClick={() => remove.mutate(preset)}><Icon name="trash" /></Button></div></div>)}</div>}{remove.error && <Problem error={remove.error} />}</section>
    <form key={`${editing?.name || 'new'}-${generation}`} className="admin-panel" onSubmit={e => { e.preventDefault(); save.mutate(new FormData(e.currentTarget)); }}><div className="admin-panel-heading"><div><h2>{editing ? '编辑标签' : '新增标签'}</h2><p>{editing ? '更新预设的展示颜色' : '一个名字，一种心情'}</p></div><Icon name={editing ? 'edit' : 'plus'} /></div><fieldset className="admin-fields" disabled={save.isPending || remove.isPending}><label>预设名称<Input name="name" placeholder="例如：日常" defaultValue={editing?.name} readOnly={!!editing} maxLength={24} required /></label><label>预设颜色<Input name="color" type="color" defaultValue={editing?.color || '#8974cc'} /></label><p className="admin-muted">预设作为默认配色；用户已保存的个人配色优先。</p><div className="management-actions"><Button className="button primary" disabled={save.isPending}>保存标签预设</Button>{editing && <Button type="button" className="button quiet" onClick={() => { setEditing(null); save.reset(); }}>取消编辑</Button>}</div>{save.error && <Problem error={save.error} />}{save.isSuccess && <p role="status">标签预设已保存</p>}</fieldset></form>
  </div>;
}
