import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { components } from '../api/schema';
import { Pager, Problem } from '../public/Public';
import { Dialog } from '../ui/Dialog';
import { columnStates } from '../columns/Columns';

type Resource = components['schemas']['Resource'];
type Action = components['schemas']['ResourceAction']['action'] | components['schemas']['ModerationAction']['action'];
const labels: Record<Action,string> = { trash:'移入回收站',restore:'恢复为私密 / 草稿',hide:'下架',unhide:'解除隐藏',approve:'通过审核',reject:'拒绝',feature:'设为精选',unfeature:'取消精选' };
export function Resources() {
  const cache = useQueryClient(); const [kind,setKind] = useState<'entry'|'column'>('column'); const [state,setState] = useState<'active'|'trash'|'pending'|'published'>('active'); const [search,setSearch] = useState(''); const [page,setPage] = useState(1);
  const [selection,setSelection] = useState<{resource:Resource;action:Action}|null>(null); const [preview,setPreview] = useState<Resource|null>(null);
  const q = useQuery({ queryKey:['admin','resources',kind,state,search,page],queryFn:({signal})=>result(client.GET('/api/v1/admin/resources',{signal,params:{query:{kind,state,search,page}}})) });
  const apply = useMutation({mutationFn:(f:FormData)=>{if(!selection) throw new Error('请选择资源');const {resource:r,action}=selection;const body={action,reason:String(f.get('reason')),version:r.version};return r.kind==='column'&&['approve','reject','hide','feature','unfeature'].includes(action) ? result(client.POST('/api/v1/admin/columns/{id}',{params:{path:{id:r.id}},body:{...body,action:action as components['schemas']['ModerationAction']['action']}})) : result(client.POST('/api/v1/admin/resources/{kind}/{id}',{params:{path:{kind:r.kind,id:r.id}},body:{...body,action:action as components['schemas']['ResourceAction']['action']}}));},onSuccess:async()=>{setSelection(null);await cache.invalidateQueries({queryKey:['admin']});}});
  return <><div className="search-toolbar"><label>资源类型<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setState('active');setPage(1);}}><option value="column">专栏</option><option value="entry">番剧</option></select></label><label>资源状态<select value={state} onChange={e=>{setState(e.target.value as typeof state);setPage(1);}}><option value="active">正常资源</option><option value="trash">回收站</option>{kind==='column'&&<><option value="pending">待审核</option><option value="published">已公开</option></>}</select></label><label className="search-field">搜索资源<input value={search} maxLength={160} onChange={e=>{setSearch(e.target.value);setPage(1);}} /></label></div>{q.isPending?<p>正在读取资源…</p>:q.error?<Problem error={q.error}/>:<><div className="admin-list">{q.data.items.map(r=><article className="admin-row" key={r.id}><h2>{r.title}</h2><p>{r.owner_name} · {r.owner_email}</p><p>{r.deleted_at?'回收站':r.kind==='column'?columnStates[r.state as keyof typeof columnStates]:r.hidden?'已隐藏':r.state}</p><div className="management-actions"><button className="button secondary" onClick={()=>setPreview(r)}>检查内容</button>{((r.deleted_at?['restore']:['trash',...(r.kind==='entry'?[r.hidden?'unhide':'hide']:r.state==='pending'?['approve','reject']:r.state==='published'?['feature','unfeature','hide']:[])]) as Action[]).map(action=><button className="button secondary" key={action} onClick={()=>{apply.reset();setSelection({resource:r,action});}}>{labels[action]}</button>)}</div></article>)}</div><Pager page={page} total={q.data.total} size={20} onChange={setPage}/></>}{selection&&<section className="admin-confirm" aria-label="确认资源操作"><h2>{labels[selection.action]}：{selection.resource.title}</h2><form className="editor-form" onSubmit={e=>{e.preventDefault();apply.mutate(new FormData(e.currentTarget));}}><label>操作说明<textarea name="reason" maxLength={400} required={!['approve','feature','unfeature'].includes(selection.action)} /></label><p>恢复不会直接重新公开内容。所有操作都会写入审计记录。</p><div className="management-actions"><button className="button primary" disabled={apply.isPending}>确认执行</button><button className="button quiet" type="button" disabled={apply.isPending} onClick={()=>setSelection(null)}>取消</button></div>{apply.error&&<Problem error={apply.error}/>}</form></section>}{preview&&<ResourcePreview resource={preview} onClose={()=>setPreview(null)}/>}</>;
}
function ResourcePreview({resource:r,onClose}:{resource:Resource;onClose:()=>void}) {
 const q=useQuery({queryKey:['admin','resource',r.kind,r.id],queryFn:({signal})=>result(client.GET('/api/v1/admin/resources/{kind}/{id}',{signal,params:{path:{kind:r.kind,id:r.id}}}))});
 return <Dialog title={r.title} onClose={onClose} wide><div className="detail-content">{q.isPending?<p>正在读取内容…</p>:q.error?<Problem error={q.error}/>: 'body' in q.data?<><p>{q.data.summary}</p><div className="preserve-lines">{q.data.body}</div><p>关联 {q.data.entry_ids.length} 部番剧</p></>:<><p>{q.data.original_title}</p><p>{q.data.details.description}</p><div className="preserve-lines">{q.data.notes}</div><p>{q.data.tags.join(' · ')}</p></>}</div></Dialog>;
}
