import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Icon } from '../components/ui/Icon';
import { formatTime } from './data';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { components } from '../api/schema';
import { Pager, Problem } from '../public/Public';
import { Dialog } from '../components/ui/Dialog';
import { columnStates } from '../columns/Columns';

type Resource = components['schemas']['Resource'];
type Action = components['schemas']['ResourceAction']['action'] | components['schemas']['ModerationAction']['action'];
const visibilityLabels: Record<string, string> = { private: '私密', unlisted: '持链接可见', public: '公开' };
const labels: Record<Action,string> = { trash:'移入回收站',restore:'恢复为私密 / 草稿',hide:'下架',unhide:'解除隐藏',approve:'通过审核',reject:'拒绝',feature:'设为精选',unfeature:'取消精选' };
function actionsFor(resource: Resource): Action[] {
  if (resource.deleted_at) return ['restore'];
  return ['trash', ...(resource.kind === 'entry' ? [resource.hidden ? 'unhide' : 'hide'] as const : resource.state === 'pending' ? ['approve', 'reject'] as const : resource.state === 'published' ? ['feature', 'unfeature', 'hide'] as const : [])];
}
export function Resources() {
  const cache = useQueryClient(); const [kind,setKind] = useState<'entry'|'column'>('column'); const [state,setState] = useState<'active'|'trash'|'pending'|'published'>('active'); const [search,setSearch] = useState(''); const [page,setPage] = useState(1);
  const [selection,setSelection] = useState<{resource:Resource;action:Action|''}|null>(null); const [preview,setPreview] = useState<Resource|null>(null);
  const q = useQuery({ queryKey:['admin','resources',kind,state,search,page],queryFn:({signal})=>result(client.GET('/api/v1/admin/resources',{signal,params:{query:{kind,state,search,page}}})) });
  const apply = useMutation({mutationFn:(f:FormData)=>{if(!selection || !selection.action) throw new Error('请选择资源与操作');const {resource:r,action}=selection;const body={action,reason:String(f.get('reason')),version:r.version};return r.kind==='column'&&['approve','reject','hide','feature','unfeature'].includes(action) ? result(client.POST('/api/v1/admin/columns/{id}',{params:{path:{id:r.id}},body:{...body,action:action as components['schemas']['ModerationAction']['action']}})) : result(client.POST('/api/v1/admin/resources/{kind}/{id}',{params:{path:{kind:r.kind,id:r.id}},body:{...body,action:action as components['schemas']['ResourceAction']['action']}}));},onSuccess:async()=>{setSelection(null);await cache.invalidateQueries({queryKey:['admin']});}});
  return <>
    <section className="admin-panel"><div className="admin-panel-heading"><div><h2>内容列表{q.data && <span className="admin-count">{q.data.total}</span>}</h2><p>检查内容后进行审核，或管理回收站资源</p></div><span className="admin-badge purple">{kind === 'entry' ? '番剧' : '专栏'}</span></div>
      <div className="admin-toolbar"><label className="admin-search"><Icon name="search" /><Input aria-label="搜索资源" placeholder="搜索内容标题…" value={search} maxLength={160} onChange={e => { setSearch(e.target.value); setPage(1); }} /></label><label className="admin-filter"><span>资源类型</span><select aria-label="资源类型" value={kind} onChange={e => { setKind(e.target.value as typeof kind); setState('active'); setPage(1); }}><option value="column">专栏</option><option value="entry">番剧</option></select></label><label className="admin-filter"><span>资源状态</span><select aria-label="资源状态" value={state} onChange={e => { setState(e.target.value as typeof state); setPage(1); }}><option value="active">正常资源</option><option value="trash">回收站</option>{kind === 'column' && <><option value="pending">待审核</option><option value="published">已公开</option></>}</select></label></div>
      {q.isPending ? <div className="admin-empty" role="status">正在读取资源…</div> : q.error ? <Problem error={q.error} /> : <><p className="admin-table-hint">左右滑动查看完整表格</p><div className="admin-table-wrap" tabIndex={0} role="region" aria-label="内容列表表格"><table className="admin-table admin-resource-table"><thead><tr><th>内容</th><th>所属用户</th><th>状态</th><th>最近更新</th><th className="admin-align-right">操作</th></tr></thead><tbody>{q.data.items.map(resource => <tr key={resource.id}><td><div className="admin-resource-title"><span className="admin-tile-icon purple"><Icon name={kind === 'entry' ? 'book' : 'edit'} /></span><strong>{resource.title}</strong></div></td><td><strong>{resource.owner_name}</strong><small>{resource.owner_email}</small></td><td><span className={`admin-badge ${resource.state === 'pending' ? 'amber' : resource.state === 'published' ? 'green' : 'neutral'}`}>{resource.deleted_at ? '回收站' : resource.kind === 'column' ? columnStates[resource.state as keyof typeof columnStates] || resource.state : resource.hidden ? '已隐藏' : visibilityLabels[resource.state] || resource.state}</span></td><td><time dateTime={resource.updated_at}>{formatTime(resource.updated_at)}</time></td><td><div className="management-actions admin-resource-actions"><Button className="button quiet" onClick={() => setPreview(resource)}>检查内容</Button><Button className="button secondary" aria-label={`管理内容 ${resource.title}`} onClick={() => { apply.reset(); setSelection({ resource, action: '' }); }}>管理</Button></div></td></tr>)}</tbody></table></div>{!q.data.items.length && <div className="admin-empty"><Icon name="book" /><h3>暂时没有{state === 'pending' ? '待审核的' : '符合条件的'}内容</h3><p>{search ? '试试其他关键词或筛选条件。' : '相关内容出现后，会展示在这里。'}</p></div>}<Pager page={page} total={q.data.total} size={20} onChange={setPage} /></>}
    </section><p className="admin-help"><Icon name="book" />恢复的内容保持私密或草稿状态，公开需要重新审核。</p>
    {selection && <Dialog title={`管理内容 · ${selection.resource.title}`} onClose={() => { if (!apply.isPending) setSelection(null); }}><form className="editor-form admin-dialog-form" onSubmit={e => { e.preventDefault(); apply.mutate(new FormData(e.currentTarget)); }}><p>{selection.resource.owner_name} · {selection.resource.owner_email}</p><label>管理操作<select aria-label="管理操作" disabled={apply.isPending} data-initial-focus value={selection.action} required onChange={e => { apply.reset(); setSelection({ ...selection, action: e.target.value as Action }); }}><option value="">请选择操作</option>{actionsFor(selection.resource).map(action => <option value={action} key={action}>{labels[action]}</option>)}</select></label><label>操作说明<textarea disabled={apply.isPending} name="reason" maxLength={400} required={!['approve', 'feature', 'unfeature'].includes(selection.action)} placeholder="填写操作原因，便于内容所有者理解" /></label><p className="admin-callout">恢复不会直接重新公开内容。所有操作都会写入审计记录。</p><div className="admin-form-actions"><Button className="button secondary" type="button" disabled={apply.isPending} onClick={() => setSelection(null)}>取消</Button><Button className={`button ${['trash', 'hide', 'reject'].includes(selection.action) ? 'danger' : 'primary'}`} disabled={!selection.action || apply.isPending}>{selection.action ? `确认${labels[selection.action]}` : '确认执行'}</Button></div>{apply.error && <Problem error={apply.error} />}</form></Dialog>}
    {preview && <ResourcePreview resource={preview} onClose={() => setPreview(null)} />}
  </>;
}

function ResourcePreview({resource:r,onClose}:{resource:Resource;onClose:()=>void}) {
 const q=useQuery({queryKey:['admin','resource',r.kind,r.id],queryFn:({signal})=>result(client.GET('/api/v1/admin/resources/{kind}/{id}',{signal,params:{path:{kind:r.kind,id:r.id}}}))});
 return <Dialog title={r.title} onClose={onClose} wide><div className="detail-content">{q.isPending?<p>正在读取内容…</p>:q.error?<Problem error={q.error}/>: 'body' in q.data?<><p>{q.data.summary}</p><div className="preserve-lines">{q.data.body}</div><p>关联 {q.data.entry_ids.length} 部番剧</p></>:<><p>{q.data.original_title}</p><p>{q.data.details.description}</p><div className="preserve-lines">{q.data.notes}</div><p>{q.data.tags.join(' · ')}</p></>}</div></Dialog>;
}
