import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { client,result } from '../api/client';
import { Problem } from '../public/Public';
const size=(n:number)=>`${(n/1024/1024).toFixed(2)} MiB`;
export function Storage(){
 const cache=useQueryClient();const [target,setTarget]=useState<'postgres'|'r2'|null>(null);
 const q=useQuery({queryKey:['admin','media'],queryFn:({signal})=>result(client.GET('/api/v1/admin/media/storage',{signal})),refetchInterval:5000});
 const change=useMutation({mutationFn:(backend:'postgres'|'r2')=>result(client.PUT('/api/v1/admin/media/storage',{body:{backend,version:q.data!.version}})),onSuccess:async()=>{setTarget(null);await cache.invalidateQueries({queryKey:['admin']});}});
 const probe=useMutation({mutationFn:()=>result(client.POST('/api/v1/admin/media/storage/probe'))});
 if(q.isPending)return <p>正在检查图片存储…</p>;if(q.error)return <Problem error={q.error}/>;
 const s=q.data;
 return <section className="settings-section"><h2>图片存储与迁移</h2><p>当前目标：{s.backend==='r2'?'Cloudflare R2':'PostgreSQL'}。数据库中 {s.postgres_images} 张，R2 中 {s.remote_images} 张，总计 {size(s.media_bytes)}。</p><p>待迁移 {s.pending} 张 · 待清理 {s.cleanup_pending} 张 · 等待重试 {s.failures} 项。迁移原图保留 {size(s.originals_bytes)}。</p><p>迁移会逐张上传并回读校验。迁移前的原图保留，可切回 PostgreSQL；迁移后新上传的图片在远端校验成功后释放数据库临时副本。图片访问继续受手账权限控制。</p>{s.configured?<><p>存储桶：{s.bucket} · {s.endpoint}</p><p>请在 Cloudflare 中保持此专用存储桶私有。连接测试会写入、读取并删除一张测试图片。</p><button className="button secondary" disabled={probe.isPending} onClick={()=>probe.mutate()}>{probe.isPending?'正在测试…':'测试 R2 读写与删除'}</button></>:<p>部署者尚未配置 R2。配置生效后可测试连接并开始迁移。</p>}{probe.data&&<p role="status">{probe.data.message}</p>}{probe.error&&<Problem error={probe.error}/>}<div className="management-actions"><button className="button secondary" disabled={!s.configured||s.backend==='r2'||change.isPending} onClick={()=>setTarget('r2')}>迁移到 R2</button><button className="button secondary" disabled={s.backend==='postgres'||change.isPending} onClick={()=>setTarget('postgres')}>切回 PostgreSQL</button></div>{target&&<div className="delete-confirm"><p>确认将图片存储切换到 {target==='r2'?'R2':'PostgreSQL'}？已有图片会在后台迁移，失败项自动重试；请保留原存储配置直到迁移和旧图清理完成。</p><button className="button primary" disabled={change.isPending} onClick={()=>change.mutate(target)}>确认切换</button><button className="button quiet" disabled={change.isPending} onClick={()=>setTarget(null)}>取消</button></div>}{change.error&&<Problem error={change.error}/>}<h3>迁移清单</h3>{s.migrations.length===0?<p>暂无迁移。</p>:<div className="admin-list">{s.migrations.map(m=><div key={m.id} className="admin-row"><span>{new Date(m.created_at).toLocaleString()} · {m.backend==='r2'?'R2':'PostgreSQL'} · {{running:'进行中',done:'完成',superseded:'已切换方向'}[m.state]} · {m.copied}/{m.total}</span><a className="button quiet" href={`/api/v1/admin/media/migrations/${m.id}`}>下载 SHA-256 清单</a></div>)}</div>}<p>完整实例备份包含 R2 图片。恢复到新实例后，图片会落入 PostgreSQL，并使用新的 R2 对象目录。</p></section>;
}
