from django.urls import path

from .views import (
    EnabledPluginListView,
    InstalledPluginListView,
    MarketplaceDetailView,
    MarketplaceView,
    MyPluginPreviewSessionView,
    MyPluginPreviewView,
    MyPluginProjectDetailView,
    MyPluginProjectView,
    MyPluginSubmissionWithdrawView,
    MyPluginSubmitView,
    MyPluginVersionUploadView,
    PluginPlatformPolicyView,
    StaffPluginCleanupView,
    StaffPluginDetailView,
    StaffPluginInstallView,
    StaffPluginListView,
    StaffPluginPublishView,
    StaffPluginReviewActionView,
    StaffPluginReviewQueueView,
    StaffPluginRevokeView,
    StaffPluginRollbackView,
    StaffPluginUnpublishView,
    UserPluginInstallationView,
)


urlpatterns = [
    path("plugins/enabled/", EnabledPluginListView.as_view(), name="enabled-plugins"),
    path("plugins/marketplace/", MarketplaceView.as_view(), name="plugin-marketplace"),
    path("plugins/marketplace/<slug:slug>/", MarketplaceDetailView.as_view(), name="plugin-marketplace-detail"),
    path("plugins/marketplace/<slug:slug>/install/", UserPluginInstallationView.as_view(), name="plugin-marketplace-install"),
    path("plugins/marketplace/<slug:slug>/installation/", UserPluginInstallationView.as_view(), name="plugin-marketplace-installation"),
    path("plugins/installed/", InstalledPluginListView.as_view(), name="plugin-installed"),
    path("plugins/policy/", PluginPlatformPolicyView.as_view(), name="plugin-platform-policy"),
    path("plugins/my/", MyPluginProjectView.as_view(), name="plugin-my-projects"),
    path("plugins/my/<int:project_id>/", MyPluginProjectDetailView.as_view(), name="plugin-my-project-detail"),
    path("plugins/my/<int:project_id>/versions/", MyPluginVersionUploadView.as_view(), name="plugin-my-version-upload"),
    path("plugins/my/versions/<int:version_id>/preview/", MyPluginPreviewView.as_view(), name="plugin-my-preview"),
    path("plugins/previews/<str:preview_session>/", MyPluginPreviewSessionView.as_view(), name="plugin-preview-session"),
    path("plugins/my/versions/<int:version_id>/submit/", MyPluginSubmitView.as_view(), name="plugin-my-submit"),
    path("plugins/my/submissions/<int:submission_id>/withdraw/", MyPluginSubmissionWithdrawView.as_view(), name="plugin-my-withdraw"),
    path("staff/plugins/", StaffPluginListView.as_view(), name="staff-plugin-list"),
    path("staff/plugins/install/", StaffPluginInstallView.as_view(), name="staff-plugin-install"),
    path("staff/plugins/cleanup/", StaffPluginCleanupView.as_view(), name="staff-plugin-cleanup"),
    path("staff/plugins/review/", StaffPluginReviewQueueView.as_view(), name="staff-plugin-review-queue"),
    path("staff/plugins/review/<int:submission_id>/", StaffPluginReviewActionView.as_view(), name="staff-plugin-review-action"),
    path("staff/plugins/versions/<int:version_id>/publish/", StaffPluginPublishView.as_view(), name="staff-plugin-publish"),
    path("staff/plugins/versions/<int:version_id>/unpublish/", StaffPluginUnpublishView.as_view(), name="staff-plugin-unpublish"),
    path("staff/plugins/versions/<int:version_id>/revoke/", StaffPluginRevokeView.as_view(), name="staff-plugin-revoke"),
    path("staff/plugins/<slug:slug>/rollback/", StaffPluginRollbackView.as_view(), name="staff-plugin-rollback"),
    path("staff/plugins/<slug:slug>/cleanup/", StaffPluginCleanupView.as_view(), name="staff-plugin-cleanup-one"),
    path("staff/plugins/<slug:slug>/", StaffPluginDetailView.as_view(), name="staff-plugin-detail"),
]
