from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .auth_views import AccountView, CompleteRegistrationView, CsrfTokenView, LogoutView, PasswordChangeView, PasswordResetConfirmView, PasswordResetView, RegisterView, StaffLoginView, VerifyRegistrationView
from .external_accounts.views import (
    ExternalAccountAuthorizeView,
    ExternalAccountCallbackView,
    ExternalAccountConnectView,
    ExternalAccountDetailView,
    ExternalAccountImportApplyView,
    ExternalAccountImportPreviewDetailView,
    ExternalAccountImportPreviewView,
    ExternalAccountListView,
    ExternalAccountVerifyView,
)
from .views import (
    ColumnViewSet,
    BangumiAutofillView,
    BangumiSearchView,
    ExportEntriesView,
    FeaturedColumnsView,
    ImportEntriesView,
    JournalEntryViewSet,
    MeView,
    MyStatsView,
    PublicShowcaseListView,
    PublicShowcaseView,
    PublicHomepageView,
    PublicJournalStatusView,
    PublicSiteSettingsView,
    PublicCatalogSearchView,
    QuickFilterViewSet,
    SharedEntryView,
    StaffColumnReviewView,
    StaffDashboardView,
    StaffPublicJournalReviewView,
    StaffSiteSettingsView,
    StaffTestEmailView,
    StaffUserPermissionsView,
    TagPresetListView,
    UserSettingsView,
)
from plugin_host.views import (
    EnabledPluginListView,
    StaffPluginCleanupView,
    StaffPluginDetailView,
    StaffPluginInstallView,
    StaffPluginListView,
    StaffPluginRollbackView,
    MarketplaceView,
    MarketplaceDetailView,
    InstalledPluginListView,
    PluginPlatformPolicyView,
    UserPluginInstallationView,
    MyPluginProjectView,
    MyPluginProjectDetailView,
    MyPluginVersionUploadView,
    MyPluginPreviewView,
    MyPluginPreviewSessionView,
    MyPluginSubmitView,
    MyPluginSubmissionWithdrawView,
    StaffPluginReviewQueueView,
    StaffPluginReviewActionView,
    StaffPluginPublishView,
    StaffPluginUnpublishView,
    StaffPluginRevokeView,
)
from .staff_views import (
    StaffBackupView,
    StaffBulkActionView,
    StaffResourceDetailView,
    StaffResourceListView,
    StaffSystemHealthView,
    StaffTagDefinitionDetailView,
    StaffTagDefinitionListCreateView,
    StaffTwoFactorView,
    StaffUserActionView,
    StaffUserDetailView,
)
from .staff_storage_views import (
    StaffMediaStorageActionView,
    StaffMediaStorageDetailView,
    StaffMediaStorageListView,
)


router = DefaultRouter()
router.register("entries", JournalEntryViewSet, basename="entry")
router.register("filters", QuickFilterViewSet, basename="filter")
router.register("columns", ColumnViewSet, basename="column")

urlpatterns = [
    path("", include(router.urls)),
    path("site-settings/", PublicSiteSettingsView.as_view(), name="site-settings"),
    path("tag-presets/", TagPresetListView.as_view(), name="tag-presets"),
    path("plugins/enabled/", EnabledPluginListView.as_view(), name="enabled-plugins"),
    path("plugins/marketplace/", MarketplaceView.as_view(), name="plugin-marketplace"),
    path("plugins/marketplace/<slug:slug>/", MarketplaceDetailView.as_view(), name="plugin-marketplace-detail"),
    path("plugins/marketplace/<slug:slug>/install/", UserPluginInstallationView.as_view(), name="plugin-marketplace-install"),
    path("plugins/marketplace/<slug:slug>/installation/", UserPluginInstallationView.as_view(), name="plugin-marketplace-installation"),
    path("plugins/installed/", InstalledPluginListView.as_view(), name="plugin-installed"),
    path("plugins/policy/", PluginPlatformPolicyView.as_view(), name="plugin-platform-policy"),
    path("plugins/my/", MyPluginProjectView.as_view(), name="plugin-my-projects"),
    path("plugins/my/<int:project_id>/", MyPluginProjectDetailView.as_view(), name="plugin-my-project-detail"),
    path("plugins/my/<int:project_id>/versions/", MyPluginVersionUploadView.as_view(), name="plugin-my-version-upload"),
    path("plugins/my/versions/<int:version_id>/preview/", MyPluginPreviewView.as_view(), name="plugin-my-preview"),
    path("plugins/previews/<str:preview_session>/", MyPluginPreviewSessionView.as_view(), name="plugin-preview-session"),
    path("plugins/my/versions/<int:version_id>/submit/", MyPluginSubmitView.as_view(), name="plugin-my-submit"),
    path("plugins/my/submissions/<int:submission_id>/withdraw/", MyPluginSubmissionWithdrawView.as_view(), name="plugin-my-withdraw"),
    path("homepage/", PublicHomepageView.as_view(), name="homepage"),
    path("auth/register/request/", RegisterView.as_view(), name="register-request"),
    path("auth/register/verify/", VerifyRegistrationView.as_view(), name="register-verify"),
    path("auth/register/complete/", CompleteRegistrationView.as_view(), name="register-complete"),
    path("auth/staff-login/", StaffLoginView.as_view(), name="staff-login"),
    path("auth/csrf/", CsrfTokenView.as_view(), name="csrf-token"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("auth/password-reset/", PasswordResetView.as_view(), name="password-reset"),
    path("auth/password-reset-confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("auth/password-change/", PasswordChangeView.as_view(), name="password-change"),
    path("auth/account/", AccountView.as_view(), name="account"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("settings/me/", UserSettingsView.as_view(), name="settings"),
    path("external-accounts/", ExternalAccountListView.as_view(), name="external-account-list"),
    path("external-accounts/<slug:provider>/connect/", ExternalAccountConnectView.as_view(), name="external-account-connect"),
    path("external-accounts/<slug:provider>/authorize/", ExternalAccountAuthorizeView.as_view(), name="external-account-authorize"),
    path("external-accounts/<slug:provider>/callback/", ExternalAccountCallbackView.as_view(), name="external-account-callback"),
    path("external-accounts/<slug:provider>/verify/", ExternalAccountVerifyView.as_view(), name="external-account-verify"),
    path("external-accounts/<slug:provider>/import-preview/", ExternalAccountImportPreviewView.as_view(), name="external-account-import-preview"),
    path("external-accounts/<slug:provider>/import-preview/<uuid:preview_id>/", ExternalAccountImportPreviewDetailView.as_view(), name="external-account-import-preview-detail"),
    path("external-accounts/<slug:provider>/import-apply/", ExternalAccountImportApplyView.as_view(), name="external-account-import-apply"),
    path("external-accounts/<slug:provider>/", ExternalAccountDetailView.as_view(), name="external-account-detail"),
    path("public-journal/status/", PublicJournalStatusView.as_view(), name="public-journal-status"),
    path("stats/me/", MyStatsView.as_view(), name="stats"),
    path("staff/dashboard/", StaffDashboardView.as_view(), name="staff-dashboard"),
    path("staff/plugins/", StaffPluginListView.as_view(), name="staff-plugin-list"),
    path("staff/plugins/install/", StaffPluginInstallView.as_view(), name="staff-plugin-install"),
    path("staff/plugins/cleanup/", StaffPluginCleanupView.as_view(), name="staff-plugin-cleanup"),
    path("staff/plugins/review/", StaffPluginReviewQueueView.as_view(), name="staff-plugin-review-queue"),
    path("staff/plugins/review/<int:submission_id>/", StaffPluginReviewActionView.as_view(), name="staff-plugin-review-action"),
    path("staff/plugins/versions/<int:version_id>/publish/", StaffPluginPublishView.as_view(), name="staff-plugin-publish"),
    path("staff/plugins/versions/<int:version_id>/unpublish/", StaffPluginUnpublishView.as_view(), name="staff-plugin-unpublish"),
    path("staff/plugins/versions/<int:version_id>/revoke/", StaffPluginRevokeView.as_view(), name="staff-plugin-revoke"),
    path("staff/plugins/<slug:slug>/rollback/", StaffPluginRollbackView.as_view(), name="staff-plugin-rollback"),
    path("staff/plugins/<slug:slug>/cleanup/", StaffPluginCleanupView.as_view(), name="staff-plugin-cleanup-one"),
    path("staff/plugins/<slug:slug>/", StaffPluginDetailView.as_view(), name="staff-plugin-detail"),
    path("staff/site-settings/", StaffSiteSettingsView.as_view(), name="staff-site-settings"),
    path("staff/site-settings/test-email/", StaffTestEmailView.as_view(), name="staff-test-email"),
    path("staff/columns/<int:pk>/review/", StaffColumnReviewView.as_view(), name="staff-column-review"),
    path("staff/public-journals/<int:pk>/review/", StaffPublicJournalReviewView.as_view(), name="staff-public-journal-review"),
    path("staff/users/<int:pk>/permissions/", StaffUserPermissionsView.as_view(), name="staff-user-permissions"),
    path("staff/resources/<str:kind>/", StaffResourceListView.as_view(), name="staff-resource-list"),
    path("staff/resources/<str:kind>/<int:pk>/", StaffResourceDetailView.as_view(), name="staff-resource-detail"),
    path("staff/bulk/<str:kind>/", StaffBulkActionView.as_view(), name="staff-bulk-action"),
    path("staff/users/<int:pk>/detail/", StaffUserDetailView.as_view(), name="staff-user-detail"),
    path("staff/users/<int:pk>/<str:action>/", StaffUserActionView.as_view(), name="staff-user-action"),
    path("staff/tags/", StaffTagDefinitionListCreateView.as_view(), name="staff-tag-list"),
    path("staff/tags/<int:pk>/", StaffTagDefinitionDetailView.as_view(), name="staff-tag-detail"),
    path("staff/system/health/", StaffSystemHealthView.as_view(), name="staff-system-health"),
    path("staff/system/backup/", StaffBackupView.as_view(), name="staff-system-backup"),
    path("staff/system/media-storage/", StaffMediaStorageListView.as_view(), name="staff-media-storage-list"),
    path("staff/system/media-storage/<int:pk>/", StaffMediaStorageDetailView.as_view(), name="staff-media-storage-detail"),
    path("staff/system/media-storage/<int:pk>/actions/", StaffMediaStorageActionView.as_view(), name="staff-media-storage-action"),
    path("staff/system/storage/", StaffMediaStorageListView.as_view(), name="staff-storage-list-alias"),
    path("staff/system/storage/<int:pk>/", StaffMediaStorageDetailView.as_view(), name="staff-storage-detail-alias"),
    path("staff/system/storage/<int:pk>/actions/", StaffMediaStorageActionView.as_view(), name="staff-storage-action-alias"),
    path("staff/security/two-factor/", StaffTwoFactorView.as_view(), name="staff-two-factor"),
    path("import/", ImportEntriesView.as_view(), name="import"),
    path("export/", ExportEntriesView.as_view(), name="export"),
    path("showcase/<uuid:public_slug>/", PublicShowcaseView.as_view(), name="showcase"),
    path("showcases/", PublicShowcaseListView.as_view(), name="showcase-list"),
    path("shared/<uuid:share_slug>/", SharedEntryView.as_view(), name="shared-entry"),
    path("featured/", FeaturedColumnsView.as_view(), name="featured"),
    path("catalog/bangumi-autofill/", BangumiAutofillView.as_view(), name="bangumi-autofill"),
    path("catalog/bangumi-search/", BangumiSearchView.as_view(), name="bangumi-search"),
    path("catalog/public-search/", PublicCatalogSearchView.as_view(), name="public-catalog-search"),
]
