import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { client, result } from '../api/client';
import type { User } from '../api/client';
import type { components } from '../api/schema';
import { Problem } from '../public/Public';
export function TwoFactor({ user, onUpdated }: { user: User; onUpdated: (u: User) => void }) {
  const [enrollment, setEnrollment] = useState<components['schemas']['TwoFactorEnrollment'] | null>(null);
  const [codes, setCodes] = useState<string[]>([]); const [action, setAction] = useState<'enable'|'disable'|'recovery'>('recovery');
  const begin = useMutation({ mutationFn: (f: FormData) => result(client.POST('/api/v1/auth/two-factor/begin', { body: { password: String(f.get('password')) } })), onSuccess: setEnrollment });
  const change = useMutation({ mutationFn: (f: FormData) => result(client.POST('/api/v1/auth/two-factor', { body: { action: user.otp_enabled ? action : 'enable', password: String(f.get('password')), code: String(f.get('code')) } })), onSuccess: data => { onUpdated(data.user); setEnrollment(null); setCodes(data.recovery_codes); } });
  return <details className="settings-section"><summary>两步验证{user.otp_enabled ? '（已开启）' : ''}</summary><p>使用验证器的 6 位动态验证码保护登录。恢复码可在验证器不可用时使用，每个仅可使用一次。</p>{codes.length > 0 && <section className="recovery-codes" aria-label="一次性恢复码"><h3>请立即保存恢复码</h3><p>关闭窗口后不再显示。请保存在与密码不同的位置。</p><pre>{codes.join('\n')}</pre><button className="button secondary" onClick={() => setCodes([])}>我已妥善保存</button></section>}{enrollment && <section className="enrollment"><p>在验证器中手动添加以下密钥：账户为 {user.email}，基于时间，6 位，30 秒。</p><label>验证器密钥<input value={enrollment.secret} readOnly autoComplete="off" /></label><a href={enrollment.uri}>在设备验证器中打开</a><p className="muted">10 分钟内填写验证码完成设置。</p></section>}<form className="editor-form compact-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (!user.otp_enabled && !enrollment) begin.mutate(f); else change.mutate(f); }}><fieldset disabled={begin.isPending || change.isPending}><label>两步验证操作密码<input name="password" type="password" autoComplete="current-password" required /></label>{user.otp_enabled && <label>安全操作<select value={action === 'enable' ? 'recovery' : action} onChange={e => setAction(e.target.value as typeof action)}><option value="recovery">重新生成恢复码</option><option value="disable">关闭两步验证</option></select></label>}{(user.otp_enabled || enrollment) && <label>验证码或恢复码<input name="code" autoComplete="one-time-code" maxLength={64} required /></label>}<p className="muted">设置成功后，其他设备会退出登录。已使用的动态验证码需要等下一轮后才能再次登录。</p><button className="button secondary">{user.otp_enabled ? '确认安全操作' : enrollment ? '验证并开启两步验证' : '生成验证器密钥'}</button></fieldset>{(begin.error || change.error) && <Problem error={begin.error || change.error} />}</form></details>;
}
