# Generated by Django 5.2.16 on 2026-08-07 12:08

import django.core.validators
import django.db.models.deletion
import journal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('japanese_title', models.CharField(blank=True, max_length=200)),
                ('airing_period', models.CharField(blank=True, max_length=50)),
                ('studio', models.CharField(blank=True, max_length=120)),
                ('episodes', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('custom_poster_url', models.URLField(blank=True, max_length=1000)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to=journal.models.poster_upload_to)),
                ('baike_url', models.URLField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tag_colors', models.JSONField(blank=True, default=dict)),
                ('personal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('watch_status', models.CharField(choices=[('completed', '看过'), ('watching', '在看'), ('planned', '想看'), ('on_hold', '搁置')], default='planned', max_length=20)),
                ('review', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', '私人'), ('unlisted', '链接可见'), ('public', '公开')], default='private', max_length=20)),
                ('share_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=journal.models.column_cover_upload_to)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过'), ('removal_requested', '申请下架')], default='draft', max_length=24)),
                ('featured', models.BooleanField(default=False)),
                ('moderation_reason', models.CharField(blank=True, default='', max_length=500)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_columns', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_columns', to=settings.AUTH_USER_MODEL)),
                ('entries', models.ManyToManyField(blank=True, related_name='columns', to='journal.journalentry')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('title_keywords', models.JSONField(blank=True, default=list)),
                ('match_mode', models.CharField(choices=[('any', '任一匹配'), ('all', '全部匹配')], default='any', max_length=10)),
                ('color', models.CharField(default='#ffe66d', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=journal.models.avatar_upload_to)),
                ('showcase_subtitle', models.CharField(blank=True, default='把每一次与动画相遇认真收藏。', max_length=240)),
                ('accent', models.CharField(default='#4ecdc4', max_length=20)),
                ('theme', models.CharField(default='memphis-pop', max_length=30)),
                ('default_view', models.CharField(default='list', max_length=10)),
                ('public_status', models.CharField(choices=[('private', '未公开'), ('pending', '待审核'), ('approved', '已公开')], default='private', max_length=16)),
                ('allow_sharing', models.BooleanField(default=False)),
                ('public_review_reason', models.CharField(blank=True, default='', max_length=500)),
                ('public_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('public_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_journals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('target_label', models.CharField(blank=True, default='', max_length=300)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='journal_adm_action_302952_idx'), models.Index(fields=['target_type', 'target_id'], name='journal_adm_target__bf0bec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'watch_status'], name='journal_jou_user_id_600cff_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['visibility', 'updated_at'], name='journal_jou_visibil_784858_idx'),
        ),
        migrations.AddIndex(
            model_name='column',
            index=models.Index(fields=['status', 'featured'], name='journal_col_status_ed2764_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quickfilter',
            unique_together={('user', 'name')},
        ),
    ]
