# Generated by Django 5.2.16 on 2026-08-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMediaIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('canonical_url', models.URLField(max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='journal.journalentry')),
            ],
            options={
                'ordering': ['provider', 'id'],
                'indexes': [models.Index(fields=['provider', 'external_id'], name='journal_ext_provider_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'provider'), name='journal_ext_entry_provider_uq')],
            },
        ),
    ]
