# Generated by Django 5.1.15 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_core_watch_history_and_metadata_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCollectionSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("baselines", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_sync_states",
                        to="journal.userexternalaccountconnection",
                    ),
                ),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_sync_state",
                        to="journal.externalmediaidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["identity_id"],
                "indexes": [
                    models.Index(fields=["connection", "updated_at"], name="journal_extsync_conn_idx"),
                ],
            },
        ),
    ]
