# Generated by Django 5.1.15 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_external_collection_sync_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalProviderConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=50, unique=True)),
                ("enabled", models.BooleanField(blank=True, null=True)),
                ("client_id", models.CharField(blank=True, default="", max_length=255)),
                ("encrypted_client_secret", models.TextField(blank=True, default="")),
                ("credential_key_version", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["provider"]},
        ),
    ]
