# Generated by Django 5.2.17 on 2026-09-08 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_reverse(apps, schema_editor):
    if apps.get_model('journal', 'JournalMediaReference').objects.using(schema_editor.connection.alias).exists():
        raise IrreversibleError('Active media holdings require a fix-forward release; their schema cannot be removed.')


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_redact_update_audit_results'),
        ('site', '0008_mediaobject_cleanup_error_mediaobject_lifecycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalMediaReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('poster_file', '上传封面'), ('custom_poster_url', '托管封面 URL')], max_length=24)),
                ('value', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_references', to='journal.journalentry')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_references', to='site.mediaobject')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_media_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'media'], name='journal_media_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'slot'), name='journal_media_entry_slot_uq'), models.CheckConstraint(condition=models.Q(('slot__in', ['poster_file', 'custom_poster_url'])), name='journal_media_slot_ck')],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
