# Generated by Django 5.2.17 on 2026-09-08 12:30

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_admission(apps, schema_editor):
    apps.get_model('journal', 'BundleRestoreAdmission').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


def require_retired_sessions(apps, schema_editor):
    if apps.get_model('journal', 'BundleRestoreSession').objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError('Portable restore sessions and receipts must be retired by bounded maintenance before downgrade.')


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('journal', '0008_journalmediareference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name='BundleRestoreAdmission',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='bundle_restore_single_admission')],
            },
        ),
        migrations.CreateModel(
            name='BundleRestoreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('state', models.CharField(choices=[('receiving', 'Receiving'), ('validating', 'Validating'), ('ready', 'Ready'), ('committing', 'Committing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='receiving', max_length=16)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('expected_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('normalized_bytes', models.PositiveBigIntegerField(default=0)),
                ('normalized_sha256', models.CharField(blank=True, max_length=64)),
                ('validator_version', models.CharField(blank=True, max_length=64)),
                ('normalized_limit', models.PositiveBigIntegerField()),
                ('single_limit', models.PositiveBigIntegerField()),
                ('index_limit', models.PositiveBigIntegerField()),
                ('reserved_bytes', models.PositiveBigIntegerField(default=0)),
                ('physical_bytes', models.PositiveBigIntegerField(default=0)),
                ('preview', models.JSONField(default=dict)),
                ('receipt', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('cleanup_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('touched_at', models.DateTimeField(auto_now_add=True)),
                ('operation_expires_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BundleRestoreChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveBigIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='journal.bundlerestoresession')),
            ],
        ),
        migrations.AddIndex(
            model_name='bundlerestoresession',
            index=models.Index(fields=['state', 'touched_at'], name='bundle_restore_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='bundlerestoresession',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='bundle_restore_owner_key'),
        ),
        migrations.AddConstraint(
            model_name='bundlerestoresession',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['receiving', 'validating', 'ready', 'committing'])), fields=('owner',), name='bundle_restore_one_open'),
        ),
        migrations.AddConstraint(
            model_name='bundlerestorechunk',
            constraint=models.UniqueConstraint(fields=('session', 'offset'), name='bundle_restore_chunk_offset'),
        ),
        migrations.RunPython(create_admission, require_retired_sessions),
    ]
