# Generated by Django 5.2.16 on 2026-08-08 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.SlugField(max_length=64)),
                ('instance_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=160)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('encrypted_secret', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['provider', 'instance_id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'instance_id'), name='integration_provider_instance_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationActionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_receipts', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'request_id'), name='integration_action_request_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentityBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=64)),
                ('external_user_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('allow_group_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identity_bindings', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['connection__provider', 'platform', 'external_user_id'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'platform', 'external_user_id'), name='integration_external_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=64)),
                ('external_user_id', models.CharField(max_length=255)),
                ('plugin_slug', models.SlugField(max_length=80)),
                ('event_name', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('route_type', models.CharField(choices=[('private', '私聊')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.integrationconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['connection', 'id'], name='integration_event_cursor_idx'), models.Index(fields=['acked_at', 'created_at'], name='integration_event_cleanup_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationPairingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_lookup', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='integrations.integrationconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', 'consumed_at', 'expires_at'], name='integration_pairing_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'code_lookup'), name='integration_pairing_lookup_uniq')],
            },
        ),
    ]
