# Generated by Django 5.2.16 on 2026-08-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='integrationactionreceipt',
            index=models.Index(fields=['status', 'completed_at'], name='integration_receipt_gc_idx'),
        ),
    ]
