d /var/lib/animemo-updater 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/bootstrap 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/cache 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/gh 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/operations 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/plans 0700 animemo-updater animemo-api -
d /var/lib/animemo-updater/releases 0700 animemo-updater animemo-api -
d /run/animemo-updater 0750 animemo-updater animemo-api -
