#!/usr/bin/env sh
set -eu
cd /opt/animemo-updater/current
export PYTHONSAFEPATH=1
export PYTHONPATH=/opt/animemo-updater/current/.runtime:/opt/animemo-updater/current
exec /usr/bin/python3 -P -B -m durability.backup_cli "$@"
