import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faArrowUp,
  faAward,
  faBolt,
  faBookmark,
  faCamera,
  faBookOpen,
  faBorderAll,
  faBowlFood,
  faChartLine,
  faCheck,
  faClockRotateLeft,
  faCircleCheck,
  faCirclePlus,
  faCloudArrowUp,
  faCompactDisc,
  faCrown,
  faChartPie,
  faChevronDown,
  faChevronUp,
  faEarthAsia,
  faEnvelope,
  faFileArrowDown,
  faFileArrowUp,
  faFilm,
  faFilter,
  faFloppyDisk,
  faGear,
  faHeart,
  faHandPointer,
  faKey,
  faLayerGroup,
  faListUl,
  faLock,
  faMagnifyingGlass,
  faPalette,
  faPenToSquare,
  faPlus,
  faPuzzlePiece,
  faQuoteLeft,
  faRightFromBracket,
  faRightToBracket,
  faRotateLeft,
  faSatelliteDish,
  faSeedling,
  faShieldHalved,
  faShareNodes,
  faSignature,
  faSliders,
  faSnowflake,
  faStar,
  faSun,
  faTableList,
  faTag,
  faTags,
  faTrash,
  faUser,
  faUserSlash,
  faUserPlus,
  faUsers,
  faUsersViewfinder,
  faWandMagicSparkles,
  faTriangleExclamation,
  faEye,
  faEyeSlash,
  faHourglassHalf,
  faHouse,
  faSpinner,
  faXmark,
  faLeaf,
  faLink,
  faLinkSlash,
} from "@fortawesome/free-solid-svg-icons";

// CSP blocks Font Awesome's runtime style injection in production. Bundle its
// official stylesheet instead so SVG sizing is identical in dev and preview.
config.autoAddCss = false;

const icons = {
  "arrow-down": faArrowDown,
  "arrow-left": faArrowLeft,
  "arrow-right": faArrowRight,
  "arrow-up-right": faArrowUpRightFromSquare,
  "arrow-up": faArrowUp,
  award: faAward,
  bolt: faBolt,
  bookmark: faBookmark,
  camera: faCamera,
  book: faBookOpen,
  grid: faBorderAll,
  "bowl-food": faBowlFood,
  "chart-line": faChartLine,
  check: faCheck,
  history: faClockRotateLeft,
  "circle-check": faCircleCheck,
  "circle-plus": faCirclePlus,
  upload: faCloudArrowUp,
  "compact-disc": faCompactDisc,
  crown: faCrown,
  chart: faChartPie,
  "chevron-down": faChevronDown,
  "chevron-up": faChevronUp,
  earth: faEarthAsia,
  envelope: faEnvelope,
  export: faFileArrowDown,
  "file-upload": faFileArrowUp,
  film: faFilm,
  filter: faFilter,
  save: faFloppyDisk,
  gear: faGear,
  heart: faHeart,
  "hand-pointer": faHandPointer,
  key: faKey,
  layers: faLayerGroup,
  list: faListUl,
  lock: faLock,
  search: faMagnifyingGlass,
  palette: faPalette,
  edit: faPenToSquare,
  plus: faPlus,
  puzzle: faPuzzlePiece,
  quote: faQuoteLeft,
  logout: faRightFromBracket,
  login: faRightToBracket,
  reset: faRotateLeft,
  "satellite-dish": faSatelliteDish,
  seedling: faSeedling,
  shield: faShieldHalved,
  share: faShareNodes,
  signature: faSignature,
  sliders: faSliders,
  snowflake: faSnowflake,
  star: faStar,
  sun: faSun,
  table: faTableList,
  tag: faTag,
  tags: faTags,
  trash: faTrash,
  user: faUser,
  "user-slash": faUserSlash,
  "user-plus": faUserPlus,
  users: faUsers,
  "users-viewfinder": faUsersViewfinder,
  eye: faEye,
  "eye-slash": faEyeSlash,
  hourglass: faHourglassHalf,
  house: faHouse,
  spinner: faSpinner,
  wand: faWandMagicSparkles,
  warning: faTriangleExclamation,
  leaf: faLeaf,
  link: faLink,
  unlink: faLinkSlash,
  close: faXmark,
};

export function Icon({ name, ...props }) {
  return <FontAwesomeIcon icon={icons[name] || faStar} {...props} />;
}
