# Generated by Django 5.2.16 on 2026-08-08 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginPackageBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('storage_path', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sha256'],
            },
        ),
        migrations.CreateModel(
            name='PluginProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('installation_mode', models.CharField(choices=[('user', '用户插件'), ('system', '系统插件')], default='user', max_length=12)),
                ('status', models.CharField(choices=[('active', '活跃'), ('suspended', '已暂停'), ('archived', '已归档')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PluginUploadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('outcome', models.CharField(default='received', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_upload_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='plugin_host_user_id_58d740_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluginVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('manifest_snapshot', models.JSONField(default=dict)),
                ('runtime_types', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('revoked', '已撤销')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_versions', to=settings.AUTH_USER_MODEL)),
                ('package_blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='plugin_host.pluginpackageblob')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='plugin_host.pluginproject')),
            ],
            options={
                'ordering': ['plugin__slug', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('security_report', models.JSONField(blank=True, default=dict)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plugin_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_submissions', to=settings.AUTH_USER_MODEL)),
                ('plugin_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='plugin_host.pluginversion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('healthy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('deployed', '已部署'), ('enabled', '已启用'), ('unhealthy', '异常'), ('revoked', '已撤销')], default='deployed', max_length=16)),
                ('system_config', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('disk_bytes', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plugin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='plugin_host.pluginproject')),
                ('current_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_deployments', to='plugin_host.pluginversion')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_deployments', to='plugin_host.pluginversion')),
            ],
            options={
                'ordering': ['plugin__slug'],
            },
        ),
        migrations.CreateModel(
            name='UserPluginInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_installations', to='plugin_host.pluginproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plugin__slug'],
            },
        ),
        migrations.CreateModel(
            name='PluginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=160)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='plugin_host.pluginproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('plugin', 'namespace', 'key'), name='plugin_data_global_key_unique'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('plugin', 'namespace', 'key', 'user'), name='plugin_data_user_key_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='pluginversion',
            constraint=models.UniqueConstraint(fields=('plugin', 'version'), name='plugin_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='pluginsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'submitted')), fields=('plugin_version',), name='plugin_submission_one_active_per_version'),
        ),
        migrations.AddConstraint(
            model_name='userplugininstallation',
            constraint=models.UniqueConstraint(fields=('user', 'plugin'), name='user_plugin_installation_unique'),
        ),
    ]
