# Generated by Django 5.2.16 on 2026-08-07 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('plugin_id', models.CharField(max_length=160, unique=True)),
                ('current_version', models.CharField(max_length=40)),
                ('previous_version', models.CharField(blank=True, default='', max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('deployed', '已部署'), ('enabled', '已启用'), ('unhealthy', '异常')], default='deployed', max_length=20)),
                ('healthy', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('disk_bytes', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PluginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_slug', models.SlugField(max_length=80)),
                ('namespace', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=160)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('plugin_slug', 'namespace', 'key'), name='plugin_data_global_key_unique'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('plugin_slug', 'namespace', 'key', 'user'), name='plugin_data_user_key_unique')],
            },
        ),
    ]
