# Generated by Django 5.2.16 on 2026-08-11 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_host', '0002_plugindeployment_rollback_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plugindata',
            index=models.Index(fields=['plugin', 'namespace', 'updated_at'], name='plugin_data_retention_idx'),
        ),
    ]
