# Generated by Django 5.2.16 on 2026-08-08 01:25

import django.db.models.deletion
import site_config.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareR2Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('warning_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('write_limit_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('encrypted_analytics_token', models.TextField(blank=True, default='', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloudflare R2 账户',
                'verbose_name_plural': 'Cloudflare R2 账户',
            },
        ),
        migrations.CreateModel(
            name='MediaStorageBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('backend_type', models.CharField(choices=[('cloudflare_r2', 'Cloudflare R2'), ('local', 'VPS 本地存储')], max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('accept_new_writes', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('warning_bytes', models.PositiveBigIntegerField(default=8000000000)),
                ('write_limit_bytes', models.PositiveBigIntegerField(default=9000000000)),
                ('config_version', models.PositiveBigIntegerField(default=1)),
                ('bucket_name', models.CharField(blank=True, default='', max_length=63)),
                ('endpoint_url', models.URLField(blank=True, default='', max_length=300)),
                ('public_base_url', models.URLField(blank=True, default='', max_length=300)),
                ('region', models.CharField(blank=True, default='auto', max_length=32)),
                ('encrypted_access_key_id', models.TextField(blank=True, default='', editable=False)),
                ('encrypted_secret_access_key', models.TextField(blank=True, default='', editable=False)),
                ('usage_payload_bytes', models.PositiveBigIntegerField(default=0)),
                ('usage_metadata_bytes', models.PositiveBigIntegerField(default=0)),
                ('usage_object_count', models.PositiveBigIntegerField(default=0)),
                ('usage_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('local_root', models.CharField(blank=True, default='', max_length=240)),
                ('local_public_base_url', models.URLField(blank=True, default='', max_length=300)),
                ('min_free_warning_bytes', models.PositiveBigIntegerField(default=16106127360)),
                ('min_free_block_bytes', models.PositiveBigIntegerField(default=10737418240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloudflare_account_ref', models.ForeignKey(blank=True, db_column='cloudflare_account_ref_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_backends', to='site.cloudflarer2account')),
            ],
            options={
                'verbose_name': '媒体存储后端',
                'verbose_name_plural': '媒体存储后端',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_backend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_objects', to='site.mediastoragebackend')),
            ],
        ),
        migrations.CreateModel(
            name='MediaStoragePoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_write_backend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_pools', to='site.mediastoragebackend')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Anime Journal', max_length=120)),
                ('homepage_title', models.CharField(default='XuanHuang 的番剧汇总', max_length=160)),
                ('site_avatar', models.ImageField(blank=True, null=True, upload_to=site_config.models.site_avatar_upload_to)),
                ('homepage_description', models.CharField(default='精心收录 2007 年至今的优质动漫作品，包含详细的题材分类、季度划分与主观评价等。', max_length=320)),
                ('universe_description', models.CharField(default='穿过各位同好们的观看轨道，发现真实同步、持续生长的私人番剧宇宙。', max_length=320)),
                ('social_handle', models.CharField(default='X: @ANIME_JOURNAL', max_length=80)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('email_delivery_enabled', models.BooleanField(default=True)),
                ('email_sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('email_sender_address', models.EmailField(blank=True, default='', max_length=254)),
                ('trusted_poster_hosts', models.JSONField(blank=True, default=site_config.models.default_trusted_poster_hosts)),
                ('resend_api_key_encrypted', models.TextField(blank=True, default='', editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homepage_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_site_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.CreateModel(
            name='TagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(choices=[('pink', '粉色'), ('rose', '玫红'), ('blue', '蓝色'), ('emerald', '翡翠'), ('amber', '琥珀'), ('orange', '橙色'), ('indigo', '靛蓝'), ('violet', '堇紫'), ('fuchsia', '洋红'), ('yellow', '黄色'), ('purple', '紫色'), ('cyan', '青色'), ('lime', '青柠'), ('sky', '天蓝'), ('slate', '灰色')], default='slate', max_length=16)),
                ('is_quick_preset', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tag_definitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tag_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '公共标签',
                'verbose_name_plural': '公共标签',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mediastoragebackend',
            constraint=models.UniqueConstraint(condition=models.Q(('backend_type', 'cloudflare_r2'), ('bucket_name__gt', ''), ('cloudflare_account_ref__isnull', False)), fields=('cloudflare_account_ref', 'bucket_name'), name='unique_r2_account_bucket_identity'),
        ),
        migrations.AddConstraint(
            model_name='mediastoragebackend',
            constraint=models.UniqueConstraint(condition=models.Q(('backend_type', 'cloudflare_r2'), ('bucket_name__gt', ''), ('endpoint_url__gt', '')), fields=('endpoint_url', 'bucket_name'), name='unique_r2_endpoint_bucket_identity'),
        ),
        migrations.AddConstraint(
            model_name='mediastoragebackend',
            constraint=models.UniqueConstraint(condition=models.Q(('backend_type', 'local')), fields=('local_root',), name='unique_local_media_storage_root'),
        ),
        migrations.AddIndex(
            model_name='mediaobject',
            index=models.Index(fields=['storage_backend', 'created_at'], name='site_mediao_storage_d5f9a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaobject',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'object_key'), name='unique_media_object_location'),
        ),
    ]
