# Generated by Django 5.2.17 on 2026-08-12

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaWriteReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_key", models.CharField(max_length=500)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "写入中"),
                            ("finalized", "已完成"),
                            ("abandoned", "已放弃"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_write_reservations",
                        to="site.mediastoragebackend",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="media_reservation_gc_idx"),
                    models.Index(fields=["storage_backend", "status"], name="media_reservation_backend_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(status="pending"),
                        fields=["storage_backend", "object_key"],
                        name="unique_pending_media_reservation",
                    ),
                ],
            },
        ),
    ]
