# Generated by Django 5.2.17 on 2026-09-08 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def guard_reverse(apps, schema_editor):
    alias = schema_editor.connection.alias
    media = apps.get_model('site', 'MediaObject')
    receipts = apps.get_model('site', 'MediaWriteReservation')
    if media.objects.using(alias).exists() or receipts.objects.using(alias).filter(status__in=['pending', 'cleanup_ready', 'cleanup_failed']).exists():
        raise IrreversibleError('Media lifecycle evidence is still in use; remove no schema and use a fix-forward release.')


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0007_turnstile_runtime_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='cleanup_error',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='lifecycle',
            field=models.CharField(choices=[('active', '可持有'), ('deleting', '正在清理'), ('delete_failed', '清理失败')], default='active', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='public_url_identity',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='public_url_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='reference_inventory_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='mediaobject', name='inventory_error',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='upload_owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediawritereservation',
            name='cleanup_error',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='mediawritereservation',
            name='status',
            field=models.CharField(choices=[('pending', '写入中'), ('finalized', '已完成'), ('abandoned', '已放弃'), ('cleanup_ready', '等待回滚清理'), ('cleanup_failed', '回滚清理失败')], default='pending', max_length=16),
        ),
        migrations.RemoveConstraint(
            model_name='mediawritereservation', name='unique_pending_media_reservation',
        ),
        migrations.AddConstraint(
            model_name='mediawritereservation',
            constraint=models.UniqueConstraint(
                fields=('storage_backend', 'object_key'),
                condition=models.Q(status__in=['pending', 'cleanup_ready', 'cleanup_failed']),
                name='unique_pending_media_reservation',
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
