import assert from 'node:assert/strict';
import { randomBytes,randomUUID,createHmac } from 'node:crypto';
import { readFile,writeFile,mkdir,cp,appendFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { installInstance,backupInstance,updateInstance,rollbackInstance,instanceStatus,removeTestInstance } from './instance.mjs';
import { checkConfiguration,checkBackupTransfer } from './instance-v11-checks.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
async function port(){const s=createServer();await new Promise((resolve,reject)=>{s.once('error',reject);s.listen(0,'127.0.0.1',resolve);});const p=s.address().port;await new Promise(resolve=>s.close(resolve));return p;}
function otp(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of secret)bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(x=>parseInt(x,2)));const data=Buffer.alloc(8);data.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac('sha1',key).update(data).digest();return String((h.readUInt32BE(h[19]&15)&0x7fffffff)%1000000).padStart(6,'0');}
function client(origin){let cookie='';return {get cookie(){return cookie;},async call(method,url,body,want=200,raw=false){const headers={Origin:origin,Cookie:cookie};if(body!==undefined)headers['Content-Type']=raw?'image/png':'application/json';const r=await fetch(origin+url,{method,headers,body:body===undefined?undefined:raw?body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const c=r.headers.get('set-cookie');if(c)cookie=c.split(';')[0];const bytes=Buffer.from(await r.arrayBuffer());assert.equal(r.status,want,`${method} ${url} returned ${r.status}: ${raw?'[binary]':bytes.toString().slice(0,200)}`);if(r.headers.get('content-type')?.includes('json'))return JSON.parse(bytes.toString());return bytes;}};}
async function config(name){return JSON.parse(await readFile(path.join(root,'.local','instances',name,'config.json'),'utf8'));}
function migrationCount(c){const result=spawnSync('docker',['exec',`${c.project}-db-1`,'psql','-U','animemo','-d',c.database,'-Atc','SELECT count(*) FROM schema_migrations'],{encoding:'utf8'});assert.equal(result.status,0);return Number(result.stdout.trim());}
export async function instanceSmoke({previousImage='animemo-next-app',image='animemo-next-app'}={}){
 const names=[0,1,2].map(()=>`probe-${randomBytes(6).toString('hex')}`),created=[];
 const report={status:'RUNNING',started_at:new Date().toISOString(),previous_image:previousImage,image,checks:[]};const output=path.join(root,'.local','output','instance-smoke.json');await mkdir(path.dirname(output),{recursive:true});
 const mark=name=>{report.checks.push(name);console.log(`Instance check: ${name}`);};
 try{
  created.push(names[0]);const a=await installInstance({name:names[0],image:previousImage,port:await port()});const old=await config(names[0]);const migrations=migrationCount(old);report.previous_image=old.image;report.migrations_before=migrations;const owner=client(a.origin);
  const credentials={email:`probe-${randomUUID()}@example.test`,password:`probe-${randomUUID()}`};await owner.call('POST','/api/v1/setup',{...credentials,display_name:'实例迁移验收',token:old.setupToken},201);
  let entry=await owner.call('POST','/api/v1/entries',{title:'跨实例保留的番剧',total_episodes:12},201);const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGMISNnyHwAE2AJoEeqx4gAAAABJRU5ErkJggg==','base64');entry=await owner.call('PUT',`/api/v1/entries/${entry.id}/cover?version=${entry.version}`,png,200,true);await owner.call('POST',`/api/v1/entries/${entry.id}/history`,{watched_on:'2026-10-07',episode_from:1,episode_to:3,request_id:randomUUID()},201);
  const enrollment=await owner.call('POST','/api/v1/auth/two-factor/begin',{password:credentials.password});const enabled=await owner.call('POST','/api/v1/auth/two-factor',{action:'enable',password:credentials.password,code:otp(enrollment.secret)});const oldCookie=owner.cookie;mark('fresh install and protected setup; real journal, image and encrypted TOTP created');
  await checkConfiguration(names[0],mark);
  let backup=await backupInstance(names[0]);const manifest=JSON.parse(await readFile(path.join(backup,'manifest.json'),'utf8'));assert.equal(manifest.schema,'animemo.instance/v3');mark('consistent custom-format PostgreSQL backup with SHA-256 and instance key');
  backup=await checkBackupTransfer(backup,names[1],old,mark);
  created.push(names[1]);const b=await installInstance({name:names[1],backup,port:await port()});const restored=client(b.origin);const stale=await fetch(b.origin+'/api/v1/auth/me',{headers:{Cookie:oldCookie}});assert.equal(stale.status,401);await restored.call('POST','/api/v1/auth/login',{...credentials,code:enabled.recovery_codes[0]});const list=await restored.call('GET','/api/v1/entries');assert.equal(list.total,1);assert.equal(list.items[0].watched_episodes,3);const picture=await restored.call('GET',`/api/v1/entries/${entry.id}/cover/${entry.cover_revision}`);assert.deepEqual(picture,png);assert.equal((await config(names[1])).secretKey,old.secretKey);mark('restore into a separate instance; old sessions revoked, encrypted TOTP and original image retained');
  const corrupted=path.join(root,'.local','output',`corrupt-backup-${randomUUID()}`);await cp(backup,corrupted,{recursive:true});await appendFile(path.join(corrupted,'database.dump'),'tampered');await assert.rejects(()=>installInstance({name:`probe-${randomBytes(6).toString('hex')}`,backup:corrupted,port:19099}),/checksum or size mismatch/);mark('corrupt backup rejected before creating Docker resources');
  const updated=await updateInstance(names[0],image);const next=await config(names[0]);report.image=next.image;report.migrations_after=migrationCount(next);report.cross_version=next.image!==old.image;assert.notEqual(next.database,old.database);assert.equal(next.rollback.database,old.database);assert.ok(report.migrations_after>=migrations);if(process.env.ANIMEMO_EXPECT_MIGRATION==='1')assert.ok(report.migrations_after>migrations,'this upgrade must add a real migration');
  const active=client(a.origin);await active.call('POST','/api/v1/auth/login',{...credentials,code:enabled.recovery_codes[0]});assert.equal((await active.call('GET','/api/v1/entries')).total,1);await active.call('POST','/api/v1/entries',{title:'更新后新增的番剧'},201);assert.equal((await active.call('GET','/api/v1/entries')).total,2);assert.ok(updated.backup);mark('update runs migrations on a new database and preserves the original database');
  await assert.rejects(()=>rollbackInstance(names[0]),/confirm-discard-new-writes/);const rollback=await rollbackInstance(names[0],true);const rolled=await config(names[0]);assert.notEqual(rolled.database,old.database);assert.equal(rolled.image,old.image);assert.equal(migrationCount(rolled),migrations);const back=client(a.origin);await back.call('POST','/api/v1/auth/login',{...credentials,code:enabled.recovery_codes[1]});assert.equal((await back.call('GET','/api/v1/entries')).total,1);mark('explicit rollback restores the previous image and schema');
  created.push(names[2]);const c=await installInstance({name:names[2],backup:rollback.rescue,port:await port()});const rescue=client(c.origin);await rescue.call('POST','/api/v1/auth/login',{...credentials,code:enabled.recovery_codes[1]});assert.equal((await rescue.call('GET','/api/v1/entries')).total,2);mark('writes after the update remain recoverable from the automatic rescue backup');
  await assert.rejects(()=>updateInstance(names[0],'postgres:17.11-bookworm'),/original image and database are running again/);const status=await instanceStatus(names[0]);assert.equal(status.image,old.image);assert.equal(status.database,rolled.database);assert.ok(status.services.some(s=>s.service==='app'&&s.health==='healthy'));assert.equal((await back.call('GET','/api/v1/entries')).total,1);mark('unhealthy candidate automatically restores the original running application');
  report.status='PASS';
 }catch(error){report.status='FAIL';report.error=error.message;throw error;}finally{
  const cleanup=[];for(const name of created.reverse()){try{await removeTestInstance(name);cleanup.push({name,removed:true});}catch(error){cleanup.push({name,removed:false,error:error.message});}}
  report.cleanup=cleanup;report.finished_at=new Date().toISOString();if(cleanup.some(x=>!x.removed))report.status='FAIL';await writeFile(output,JSON.stringify(report,null,2)+'\n');if(cleanup.some(x=>!x.removed))throw new Error('One or more isolated test instances were not cleaned up; see the instance-smoke report.');
 }
 return report;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const previousImage=process.env.ANIMEMO_PREVIOUS_IMAGE||'animemo-next-app',image=process.env.ANIMEMO_CANDIDATE_IMAGE||'animemo-next-app';instanceSmoke({previousImage,image}).then(r=>console.log(`Instance operations ${r.status}`)).catch(e=>{console.error(e.message);process.exitCode=1;});
}
